name: Update Release Draft

on:
  pull_request:
    types: [closed] # Trigger when a PR is closed

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if PR is merged
        id: check_merged
        run: |
          if [[ "${{ github.event.pull_request.merged }}" != "true" ]]; then
            echo "PR was not merged. Skipping release draft update."
            exit 0  # Exit without failure if the PR is not merged
          fi

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: "release-drafter.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}